// src/pages/404.vue
<template>
  <Layout>
    <section class="section">
      <div class="container">
        <h1 class="title is-1">404</h1>

        <p class="is-size-5">
          Whoops, you've hit a dead end. Maybe you want to go back <g-link to="/">Home</g-link>?
        </p>
      </div>
    </section>
  </Layout>
</template>

<script>
export default {
  metaInfo: {
    title: '404'
  }
}
</script>

// src/pages/404.jsx
import { Link } from 'gatsby';
import * as React from 'react';
import { Container } from 'react-bootstrap';
import Layout from '../components/layout';

const NotFoundPage = () => (
  <Layout title="Not Found">
    <section>
      <Container>
        <h1 className="title">404</h1>
        <p className="lead">
          Whoops, you've hit a dead end. Would you like to go back <Link to="/">home</Link>?
        </p>
      </Container>
    </section>
  </Layout>
);

export default NotFoundPage;
