// src/pages/blog.jsx
import * as React from 'react';
import { Container } from 'react-bootstrap';
import { graphql } from 'gatsby';
import Layout from '../components/layout';
import PostCard from '../components/post-card';

const BlogPage = ({ data }) => (
  <Layout title="Blog">
    <section>
      <Container>
        <h1 className="title">Blog</h1>
        {
            data.allMdx.edges.map(({ node }) => (
              <PostCard key={node.id} post={node} />
            ))
          }
      </Container>
    </section>
  </Layout>
);

export const query = graphql`
  query {
    allMdx(sort: {fields: frontmatter___date, order: DESC}) {
      edges {
        node {
          id
          frontmatter {
            slug
            title
            date(formatString: "D MMM YYYY")
            description
            feature {
              image {
                childImageSharp {
                  gatsbyImageData(layout: FULL_WIDTH)
                }
              }
            }
          }
          excerpt
          timeToRead
        }
      }
    }
    site {
      siteMetadata {
        siteUrl
        author
      }
    }
  }
`;

export default BlogPage;

// src/pages/Blog.vue
<template>
  <Layout>
    <div class="container mx-auto py-5">
      <PostList v-for="year in years" :key="year" :year="year" />
    </div>
  </Layout>
</template>

<script>
import PostList from "@/components/PostList";

export default {
  metaInfo: {
    title: 'Blog'
  },
  components: {
    PostList
  },
  computed: {
    years() {
      const years = {};
      const posts = this.$page.posts.edges;
      posts.map((post) => {
        const year = post.node.date.split(" ")[2];
        years[year] = "";
      });
      return Object.keys(years).sort((a, b) => {
        return b - a;
      });
    }
  }
}
</script>

<page-query>
query {
  posts: allBlogPost(filter: { date: { gte: "2020" }}) {
    totalCount
    edges {
      node {
        id
        title
        timeToRead
        description
        date (format: "D MMM YYYY")
        path
      }
    }
  }
}
</page-query>
